### ISSUE TITLE
[Feature Request]: Expose React-Query's useInfiniteQuery hook in ZodiosHooks

### ISSUE THREAD

**Issue by er1chu** [ecyrbe/zodios-react#98]
## Describe the feature you'd like to request

Would love a way to access `useInfiniteQuery` via Zodios Hooks

Example:
```
const {
  data: posts
  fetchNextPage,
  fetchPreviousPage,
  hasNextPage,
  hasPreviousPage,
  isFetchingNextPage,
  isFetchingPreviousPage,
  isLoading,
  isError,
} = zodiosHooks.useInfiniteQuery("/posts");

```

**Comment by ecyrbe** [comment]
Yes, Indeed.
That should be easy.

**Comment by ecyrbe** [comment]
@er1chu After thinking a little about this, here is the design i think should work.

```ts
const {
  data: posts
  fetchNextPage,
  fetchPreviousPage,
  hasNextPage,
  hasPreviousPage,
  isFetchingNextPage,
  isFetchingPreviousPage,
  isLoading,
  isError,
} = zodiosHooks.useInfiniteQuery("/posts", { 
  queries: {
    limit: 10
  },
  {
    getNextPageParam: (lastPage, allPages) => ({ // zodios compatible config
      queries: {
        page: lastPage.page+1,
      }
    })
  }
});
```

since any parameter can be used to handle page fetching, you will need to make your getNextPageParam return an object that Satisfies the `ZodiosOptions` parameters, but where everything is optional. 
These options will be merged by zodios with your provided ones (here the `limit` and `page` attributes will be merged into the options when fetching more pages).

There is just one tricky part. Internally, zodios is still using react-query . Zodios is using the provided options to autogenerate a query key, so that you don't need to handle it.
But here, we don't want the `page` attribute to be used in the query key, because then react-query will consider the calls to be different, and will instead load your `page 2` instead of appending it.

I have to think a little about this tricky part. How could zodios know at runtime before calling the first page, that `page` attribute will be used as the key to handle infinite page load and then ignore it on the QueryKey.

1. One idea could be that zodios could call `getNextPageParam` and `getPrevPageParam` with fake data to get the keys be known at first execution, not just for getting the next page. I don't think this is technically easy. generating fake data that satisfies the expected contract seems really overkill
2. another idea, it let the caller specify the parameters that `getNextPageParam`/`getPrevPageParam` should return. like this :  
```ts
zodiosHooks.useInfiniteQuery("/posts", { 
  queries: {
    limit: 10
  },
  {
    getPageParam: () => ([
      "page"
    ]),
    getNextPageParam: (lastPage, allPages) => ({ // zodios compatible config
      queries: {
        page: lastPage.page+1,
      }
    })
  }
});
```

I'm thinking implementing the second use case.
What do you think ?

**Comment by er1chu** [comment]
I think second use case is better! Less batteries included!

**Comment by ecyrbe** [comment]
@er1chu you can check v9.1.0 of `@zodios/react`. it has an implementation of `useInfinitQuery`.
You can check documentation example [here](http://www.zodios.org/docs/client/react#zodiosuseinfintequery)

**Comment by er1chu** [comment]
Wow that was quick thank you so much!
